### ISSUE TITLE
[BUG]: Not working on macOS

### ISSUE THREAD

**Issue by Fyroeo** [Just1truc/Abricot-Norminette#28]
### What happened?

Abricot is not working anymore on macOS as cat -A is not a valid option

### Version

Yes

### What OS are you seeing the problem on?

macOS

### Relevant output

```shell
cat: illegal option -- A
usage: cat [-belnstuv] [file ...]
Traceback (most recent call last):
  File "/usr/local/lib/Abricot_scripts/brico.py", line 847, in <module>
    main()
  File "/usr/local/lib/Abricot_scripts/brico.py", line 845, in main
    rule.run()
  File "/usr/local/lib/Abricot_scripts/brico.py", line 766, in run
    self.browse_directory(os.listdir("."), ".")
  File "/usr/local/lib/Abricot_scripts/brico.py", line 661, in browse_directory
    obj.run(self, paths + "/" + files)
  File "/usr/local/lib/Abricot_scripts/brico.py", line 381, in run
    result = subprocess.check_output("cat -A "+files, shell=True)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cat -A ./test.c' returned non-zero exit status 1.
```

**Comment by Fyroeo** [comment]
Hello @Fyroeo,
As you're incredible, you've fixed the problem by yourself.
Well done bro !
